#camera parameters
ip: '169.254.169.138'
port: 6340
protocol: 3
use_ros: True

#streaming parameters
distance: 3500 #mm
minFrequency: 18500
maxFrequency: 55000
camera_W: 640
camera_H: 480
acimageFPS: 50 #fps
acAvg: 0 #0 - fast 1 - slow 2 - impulse
deviceState: 5 #0-Idle 1-Measuring 2-Streaming 3-Service_1 4-Ultrasonic 5-Ultrasonic+
dataToSend1: 75 #11010010 (75) (data) -> AcVid, Vid, ThermalVid, LocalSound, MicLevels, MicRaw, Spectra, SingleMic
dataToSend2: 1 #1000000 (filters) -> LocalSound, LevelFiltered, RawDataFiltered, IRGain
heartbeatRate: 300 #Hz
cameraLighting: 0 #0-off 1-on
videoFPS: 30 #fps

#Acoustic Video config
scalingMode: 2 #0-off, 1-Auto (scale with respect to the max in the set region), 2-Smart
dynamic: 10.0 #dB
maximum: 54.2 #dB if 0 -> use the max of last 10 seconds
crest: 15.0 #dB [5 - 15]



publishVideo: True
publishAcVideo: True
publishSpectrum: True
publishAudio: True
publishThermal: True
publishOverlay: True #unused

#visualization parameters
visualizeVideo: False
visualizeThermal: False
visualizeAudio: False

visualizeAcVideo: True
minimum_db: 0
maximum_db: 120

visualizeSpectrum: False
minimum_spdb: -120 
maximum_spdb: 120

#post-processing
visualizeOverlay: False  #forces(sets) -> visualizeVideo
overlayConfig: '0000' # [Acoustic, Spectrum, Audio, Thermal]

#camera topics
camera_topic: /state

#service servers
server_name: /SoundcamServer

#stream topics
video_topic: /video
acousticvideo_topic: /video/acoustic
spectrum_topic: /spectrum
audio_topic: /audio
thermalvideo_topic: /video/thermal

