#camera parameters
ip: '169.254.169.138'
port: 6340
protocol: 3
use_ros: True

#streaming parameters
distance: 3500 #mm
minFrequency: 4300
maxFrequency: 67700
camera_W: 640
camera_H: 480
acimageFPS: 50 #fps
acAvg: 0 #0 - fast 1 - slow 2 - impulse
deviceState: 5 #0-Idle 1-Measuring 2-Streaming 3-Service_1 4-Ultrasonic 5-Ultrasonic+
dataToSend: 75 #11010010
heartbeatRate: 300 #Hz
cameraLighting: 0 #0-off 1-on
videoFPS: 30 #fps

publish_video: True
publish_acoustic_video: True
publish_spectrum: True
publish_audio: True
publish_thermal: True

#post-processing
publish_video_acoustic_overlay: False

#visualization parameters
visualize_audio: False
minimum_value: -300000
maximum_value: 300000

visualize_video: False

visualize_acoustic_video: False
minimum_db: 0
maximum_db: 100

visualize_spectrum: False
minimum_frequency: -120
maximum_frequency: 120


#camera topics
camera_topic: /state

#service servers
server_name: /SoundcamServer

#stream topics
video_topic: /video
acousticvideo_topic: /video/acoustic
spectrum_topic: /spectrum
audio_topic: /audio
thermalvideo_topic: /video/thermal

